# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-01 13:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u76ee\u5f55\u540d\u79f0')),
                ('slug', models.SlugField(max_length=200, verbose_name='\u76ee\u5f55\u94fe\u63a5')),
                ('desc', models.TextField(blank=True, verbose_name='\u76ee\u5f55\u63cf\u8ff0')),
                ('publisher', models.CharField(max_length=100, verbose_name='\u53d1\u5e03\u8005')),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u4ea7\u54c1\u76ee\u5f55',
                'verbose_name_plural': '\u4ea7\u54c1\u76ee\u5f55',
            },
        ),
        migrations.CreateModel(
            name='CatalogCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u76ee\u5f55\u540d\u79f0')),
                ('slug', models.SlugField(max_length=100, verbose_name='\u76ee\u5f55\u94fe\u63a5')),
                ('desc', models.TextField(blank=True, verbose_name='\u76ee\u5f55\u63cf\u8ff0')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='product.Catalog', verbose_name='\u5206\u7c7b\u76ee\u5f55')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.CatalogCategory', verbose_name='\u4e0a\u7ea7\u76ee\u5f55')),
            ],
            options={
                'verbose_name': '\u4ea7\u54c1\u7ba1\u7406',
                'verbose_name_plural': '\u4ea7\u54c1\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u540d\u79f0')),
                ('slug', models.SlugField(max_length=100, verbose_name='\u94fe\u63a5')),
                ('desc', models.TextField(verbose_name='\u63cf\u8ff0')),
                ('photo', models.ImageField(upload_to=product.models.product_directory_path, verbose_name='\u56fe\u7247')),
                ('manufacturer', models.CharField(blank=True, max_length=300, verbose_name='\u4f9b\u5e94\u5546')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='\u4ef7\u683c')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.CatalogCategory', verbose_name='\u76ee\u5f55')),
            ],
            options={
                'verbose_name': '\u4ea7\u54c1\u5217\u8868',
                'verbose_name_plural': '\u4ea7\u54c1\u5217\u8868',
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u5c5e\u6027\u540d')),
                ('desc', models.TextField(blank=True, verbose_name='\u5c5e\u6027\u63cf\u8ff0')),
            ],
            options={
                'verbose_name': '\u4ea7\u54c1\u5c5e\u6027',
                'verbose_name_plural': '\u4ea7\u54c1\u5c5e\u6027',
            },
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=150, verbose_name='\u5c5e\u6027\u503c')),
                ('desc', models.TextField(blank=True, verbose_name='\u63cf\u8ff0')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductAttribute', verbose_name='\u5c5e\u6027\u540d')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='product.Product', verbose_name='\u4ea7\u54c1')),
            ],
            options={
                'verbose_name': '\u4ea7\u54c1\u8be6\u60c5',
                'verbose_name_plural': '\u4ea7\u54c1\u8be6\u60c5',
            },
        ),
    ]
